version = 0.1

[default]
[default.global.parameters]
stack_name = "echofriendly-backend"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "echofriendly"
stack_name = "echofriendly"
image_repositories = []
